# Generated by Django 2.2.7 on 2019-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=50, verbose_name='Given name')),
                ('family_name', models.CharField(max_length=50, verbose_name='Family name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Balance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.BankAccountOwner', verbose_name='Account owner')),
            ],
        ),
    ]
