# Generated by Django 2.2.7 on 2019-11-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='bankaccounts.BankAccount', verbose_name='Account')),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote', to='bankaccounts.BankAccount', verbose_name='Remote account')),
            ],
        ),
    ]
