# Generated by Django 2.2.7 on 2019-12-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='bankaccounts.BankAccount', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote', to='bankaccounts.BankAccount', verbose_name='Remote account'),
        ),
    ]
